// Mocks generated by Mockito 5.4.4 from annotations
// in fidelux/test/pairing/pairing_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i5;

import 'package:fidelux/domain/entities/crypto_identity.dart' as _i4;
import 'package:fidelux/domain/repositories/key_storage_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [KeyStorageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockKeyStorageRepository extends _i1.Mock
    implements _i2.KeyStorageRepository {
  MockKeyStorageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> savePrivateKey(
    _i4.Role? role,
    _i5.Uint8List? privateKey,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePrivateKey,
          [
            role,
            privateKey,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i5.Uint8List?> loadPrivateKey(_i4.Role? role) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadPrivateKey,
          [role],
        ),
        returnValue: _i3.Future<_i5.Uint8List?>.value(),
      ) as _i3.Future<_i5.Uint8List?>);

  @override
  _i3.Future<void> savePublicKey(
    _i4.Role? role,
    _i5.Uint8List? publicKey,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePublicKey,
          [
            role,
            publicKey,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i5.Uint8List?> loadPublicKey(_i4.Role? role) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadPublicKey,
          [role],
        ),
        returnValue: _i3.Future<_i5.Uint8List?>.value(),
      ) as _i3.Future<_i5.Uint8List?>);

  @override
  _i3.Future<void> savePeerPublicKey(
    _i4.Role? peerRole,
    _i5.Uint8List? publicKey,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePeerPublicKey,
          [
            peerRole,
            publicKey,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i5.Uint8List?> loadPeerPublicKey(_i4.Role? peerRole) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadPeerPublicKey,
          [peerRole],
        ),
        returnValue: _i3.Future<_i5.Uint8List?>.value(),
      ) as _i3.Future<_i5.Uint8List?>);

  @override
  _i3.Future<void> deleteAll() => (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
