// Mocks generated by Mockito 5.4.4 from annotations
// in fidelux/test/email/message_validator_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i5;

import 'package:fidelux/domain/entities/crypto_identity.dart' as _i2;
import 'package:fidelux/domain/repositories/crypto_repository.dart' as _i3;
import 'package:fidelux/domain/repositories/key_storage_repository.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCryptoIdentity_0 extends _i1.SmartFake
    implements _i2.CryptoIdentity {
  _FakeCryptoIdentity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CryptoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCryptoRepository extends _i1.Mock implements _i3.CryptoRepository {
  MockCryptoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.CryptoIdentity> generateIdentity(_i2.Role? role) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateIdentity,
          [role],
        ),
        returnValue: _i4.Future<_i2.CryptoIdentity>.value(_FakeCryptoIdentity_0(
          this,
          Invocation.method(
            #generateIdentity,
            [role],
          ),
        )),
      ) as _i4.Future<_i2.CryptoIdentity>);

  @override
  _i4.Future<String> sign(
    _i5.Uint8List? message,
    _i5.Uint8List? privateKey,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sign,
          [
            message,
            privateKey,
          ],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #sign,
            [
              message,
              privateKey,
            ],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<bool> verify(
    _i5.Uint8List? message,
    String? signatureBase64,
    _i5.Uint8List? publicKey,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verify,
          [
            message,
            signatureBase64,
            publicKey,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  String sha256Hash(String? input) => (super.noSuchMethod(
        Invocation.method(
          #sha256Hash,
          [input],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #sha256Hash,
            [input],
          ),
        ),
      ) as String);
}

/// A class which mocks [KeyStorageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockKeyStorageRepository extends _i1.Mock
    implements _i7.KeyStorageRepository {
  MockKeyStorageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> savePrivateKey(
    _i2.Role? role,
    _i5.Uint8List? privateKey,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePrivateKey,
          [
            role,
            privateKey,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i5.Uint8List?> loadPrivateKey(_i2.Role? role) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadPrivateKey,
          [role],
        ),
        returnValue: _i4.Future<_i5.Uint8List?>.value(),
      ) as _i4.Future<_i5.Uint8List?>);

  @override
  _i4.Future<void> savePublicKey(
    _i2.Role? role,
    _i5.Uint8List? publicKey,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePublicKey,
          [
            role,
            publicKey,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i5.Uint8List?> loadPublicKey(_i2.Role? role) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadPublicKey,
          [role],
        ),
        returnValue: _i4.Future<_i5.Uint8List?>.value(),
      ) as _i4.Future<_i5.Uint8List?>);

  @override
  _i4.Future<void> savePeerPublicKey(
    _i2.Role? peerRole,
    _i5.Uint8List? publicKey,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePeerPublicKey,
          [
            peerRole,
            publicKey,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i5.Uint8List?> loadPeerPublicKey(_i2.Role? peerRole) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadPeerPublicKey,
          [peerRole],
        ),
        returnValue: _i4.Future<_i5.Uint8List?>.value(),
      ) as _i4.Future<_i5.Uint8List?>);

  @override
  _i4.Future<void> deleteAll() => (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
